
name: MythicRaids
version: 1.0
main: me.mrmadara.mythicraids.MythicRaids
api-version: 1.20
commands:
  raid:
    description: Inicia uma raid.
    usage: /raid start <nome>
permissions:
  mythicraids.admin:
    description: Permissão para administrar raids.
    default: op
